#!/bin/sh

set -e
. /root/.nvm/nvm.sh
nvm use 10
export NPM_CONFIG_LOGLEVEL=error
cd /tmp
npm init -y
npm i aws-sdk@latest
node-prune node_modules
npx modclean -r
zip -yr /tmp/aws-sdk.zip ./node_modules/
